services:
 vue-frontend:
    build: ./vue-frontend
    ports:
      - "8080:80"
    volumes:
      - ./vue-frontend:/app
      - /app/node_modules
    depends_on:
      - node-backend
  node-backend:
    build: ./node-backend/backend-node
    ports:
      - "4242:4242"
    volumes:
      - ./node-backend/backend-node:/app
      - /app/node_modules
    depends_on:
      - python-recs
    command: node -e "const http = require('http'); const server = http.createServer((req, res) => { res.writeHead(200); res.end('Node.js is running!'); }); server.listen(4242, () => console.log('Server running on port 4242'));"

 Copypython-recs:
  build: ./python-recs
  ports:
    - "8000:8000"
  volumes:
    - ./python-recs:/app
  command: python app.py
  environment:
    - FLASK_ENV=development

    mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ecommerce

volumes:
  mongo-data:


  services:
  vue-frontend:
    # ...
    environment:
      - VUE_APP_API_URL=http://node-backend:4242
      - VUE_APP_RECOMMENDATIONS_URL=http://python-recs:8000

  node-backend:
    # ...
    environment:
      - PYTHON_SERVICE_URL=http://python-recs:8000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/ecommerce?authSource=admin

  python-recs:
    # ...
    environment:
      - NODE_BACKEND_URL=http://node-backend:4242

      vue-frontend:
  # ...
  command: npm run serve
  environment:
    - NODE_ENV=development  

    node-backend:
  # ...
  command: npm run dev  # This uses nodemon
  environment:
    - NODE_ENV=development

    python-recs:
  # ...
  environment:
    - FLASK_ENV=development
    - FLASK_DEBUG=1